# Site settings
title: Eunae's Garden
baseurl: ""
url: "Mia-estudiante.github.io/"
# google_analytics: G-REVP5X32M5 # Tracking ID, e.g. "UA-000000-01"
# remote_theme: chesterhow/tale

# Author
author:
  name: Eunae Kang
  desc: Welcome😃
  email: eunae.engineer@gmail.com
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: Test
  flickr:
  github: Mia-estudiante
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/eunae-kang-101226255/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: Test
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
# permalink: https://pasoapaso.tistory.com/
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
